### 결제 요청
POST http://localhost:8080/payment/request
Authorization: Public-Key
Content-Type: application/json

{
  "customerId": "customerId",
  "orderId": "orderId",
  "price": 100000,
  "type": "CARD",
  "successUrl": "http://localhost:8080/success",
  "failUrl": "http://localhost:8080/fail",
  "paymentMethodDetails": {
      "cardNumber": "1234-1234-1234-1234",
      "cvc": "123",
      "expireDate": "02/27",
      "cardCompany": "030",
      "installmentPeriod": 0
  }
}

### 결제 승인
POST http://localhost:8080/payment/12345/confirm
Authorization: Public-Key
Content-Type: application/json

{
  "customerId": "customerId",
  "orderId": "orderId",
  "paymentId": "123e4567-e89b-12d3-a456-426614174000",
  "transactionId": "987e6543-e89b-12d3-a456-426614174111",
  "type": "CARD",
  "paymentApproveDetails": {
    "installmentPeriod": 3,
    "price": 50000,
    "cardIdentityCertifyNumber": "cert1234"
  },
  "paymentMethodDetails" :{
    "cardNumber": "1234-5678-9012-3456",
    "cvc": "123",
    "expireDate": "12/26",
    "cardCompany": "030"
  }
}


### 결제 취소
PUT http://localhost:8080/payment/12345/cancel
Authorization: Public-Key
Content-Type: application/json

{
  "customerId": "customerId",
  "paymentId": "123e4567-e89b-12d3-a456-426614174000",
  "transactionId": "987e6543-e89b-12d3-a456-426614174111",
  "type": "CARD"
}


### 결제 환불
PUT http://localhost:8080/payment/12345/reject
Authorization: Public-Key
Content-Type: application/json

{
  "customerId": "customerId",
  "paymentId": "123e4567-e89b-12d3-a456-426614174000",
  "transactionId": "987e6543-e89b-12d3-a456-426614174111",
  "type": "CARD"
}

### 카드 리스트 확인
GET http://localhost:8080/cards
Authorization: Public-Key

### 결제 정보 확인
GET http://localhost:8080/payment/12345
Authorization: Secret-Key

### 거래 정보 확인
GET http://localhost:8080/payment/seller/56789
Authorization: Secret-Key


### 거래 정보 확인
GET http://localhost:8080/payment/transaction/67890
Authorization: Secret-Key